"""Schemas for retrieval-augmented chat responses."""

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """A user question to answer from indexed document context."""

    question: str = Field(description="Natural-language question about uploaded documents.")


class ChatResponse(BaseModel):
    """A grounded answer and provenance from retrieved document chunks."""

    question: str = Field(description="Original user question.")
    answer: str = Field(description="Grounded final answer generated by the local LLM.")
    sources: list[str] = Field(description="Unique source document filenames used as context.")
    retrieved_chunks: int = Field(description="Number of retrieved chunks supplied to the LLM.")
